TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.8
  acc_lim_theta: 3.2
  acc_lim_x: 3.0
  acc_lim_y: 3.0
  holonomic_robot: false
  
  sim_time: 1.5
  sim_granularity: 0.025   
  
  vx_samples: 8
  vtheta_samples: 20
  
  xy_goal_tolerance: 0.2  
  yaw_goal_tolerance: 0.09
 
