obstacle_range: 6.0
raytrace_range: 8.5
footprint: [[-0.12, -0.14], [-0.12, 0.14], [0.12, 0.14], [0.12, -0.14]]
footprint_padding: 0.079
inflation_radius: 0.55
transform_tolerance: 0.5

observation_sources: scan
scan:
  data_type: LaserScan
  topic: ebot/laser/scan
  marking: true
  clearing: true

map_type: costmap

