DWAPlannerROS:
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_vel_theta: 6.0
  min_vel_theta: 5.0
  min_in_place_vel_theta: 20
  acc_lim_theta: 15
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  holonomic_robot: false
  
  sim_time: 1.5
  sim_granularity: 0.025   
  
  vx_samples: 8
  vtheta_samples: 20
  
  xy_goal_tolerance: 0.2  
  yaw_goal_tolerance: 0.09
 
