# choosing whether to stop the costmap node when move_base is inactive
shutdown_costmaps: false
# cycle of control iteration (in Hz) that orders the speed command to the robot base
controller_frequency: 3.0
# maximum time (in seconds) that the controller will listen for control information before the 
space-clearing operation is performed
controller_patience: 1.0 
# repetition cycle of global plan (in Hz)
planner_frequency: 2.0
# maximum amount of time (in seconds) to wait for an available plan before the space-clearing
operation is performed
planner_patience: 1.0
# time (in sec) allowed to allow the robot to move back and forth before executing the recovery 
behavior.
oscillation_timeout: 10.0
# oscillation_timeout is initialized if you move the distance below the distance (in meter) that 
the robot should move so that it does not move back and forth.
oscillation_distance: 0.2 
# Obstacles farther away from fixed distance are deleted on the map during costmap initialization 
of the restore operation
conservative_reset_dist: 0.1
